[package]
name = "log_lastfm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustfm-scrobble = "1.1.1"
serde = "1.0.192"
toml = "0.8.8"
